### ISSUE TITLE
RoR group project: set up Kanban board 🚀 

### ISSUE THREAD

**Issue by ismailmunyentwari9** [zeff96/ror_group_project#1]
# Requesting for review  ♻️ 
<h2>Greetings to you dear Reviewer. we are the team of 👥 </h2>

- <a href ="https://github.com/ismailmunyentwari9">`Ismail`</a>
- <a href ="https://github.com/zeff96">`Adeka`</a>
- <a href ="https://github.com/QueenterJuma">`Queen`</a>
We have followed the project requirements of installing kanban board 
and we are here now kindly to ask you to review our hardworking results
of this <a href ="https://github.com/zeff96/ror_group_project">project</a>

**Comment by rloterh** [comment]
Hi Team, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on, but you are almost there! 
🏁  🌴 🚦 🚗 🏫  🏡   _🏃 🏃  🌴 🌴 

## Highlights 👍  
- Tasks distributed fairly!

## Required Changes ♻️
- [x] Like in the previous boards, kindly ensure that the following columns are added to the board:
  * To Do
  * In Progress
  * In Review
  * Done

- [ ] Some of your cards do not have descriptions. Kindly ensure to add descriptions to those cards appropriately.

**No description provided:**
![image](https://github.com/zeff96/ror_group_project/assets/12745474/80b13e2f-d5e1-43f8-97b4-993a65486ec0)

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ismailmunyentwari9** [comment]
> Hi Team,
> 
> You did extremely great on this project! 👏 👏 There are however a few issues that you still need to work on, but you are almost there! 🏁 🌴 🚦 🚗 🏫 🏡 _🏃 🏃 🌴 🌴
> 
> ## Highlights 👍
> * Tasks distributed fairly!
> 
> ## Required Changes ♻️
> * [x]  Like in the previous boards, kindly ensure that the following columns are added to the board:
>   
>   * To Do
>   * In Progress
>   * In Review
>   * Done
> * [ ]  Some of your cards do not have descriptions. Kindly ensure to add descriptions to those cards appropriately.
> 
> **No description provided:** ![image](https://user-images.githubusercontent.com/12745474/248844406-80b13e2f-d5e1-43f8-97b4-993a65486ec0.png)
> 
> Cheers and Happy coding!👏 💻 🍷
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hello Sir, I would like kindly to double check that the columns you suggested to add are already there
![Screenshot (126)](https://github.com/zeff96/ror_group_project/assets/79504482/37501ce0-b736-489b-ba7b-3c3935679dc6)

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Please always  add the link to your Github  project (kanban board) in your issue 👍🏿 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zeff96** [comment]
closed
